name: mvvm_boilerplate
description: Model View ViewModel Boilerplate code.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.11.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    flutter_svg: ^0.22.0
    fluttertoast: ^8.0.7
    get_it: ^7.1.3
    http: ^0.13.3
    intl: ^0.17.0
    material_design_icons_flutter: ^4.0.5955
    provider: ^5.0.0
    sprintf: ^6.0.0
    connectivity: ^3.0.6

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/icons/

    fonts:
        - family: OpenSans
          fonts:
              - asset: assets/fonts/OpenSans-Regular.ttf
              - asset: assets/fonts/OpenSans-Italic.ttf
                style: italic
              - asset: assets/fonts/OpenSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
                weight: 600
                style: italic
